config:
  springProfilesActive: dev  
  jpa:
    showSql: "true"
  management:
    endpointsInclude: "*"  
  logging:
    levelRoot: "INFO"
    levelApp: "DEBUG"
    levelSpringWeb: "INFO"
    levelSpringSecurity: "DEBUG"

  swagger:
    enabled: "true"

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 256Mi