apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secrets
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.database.username | quote }}
  DB_PASSWORD: {{ .Values.secrets.database.password | quote }}