apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    name: http
  - name: grpc
    port: {{ .Values.grpc.port }}
    targetPort: {{ .Values.grpc.targetPort }}
    protocol: TCP
  selector:
    app: booking-service